spring.application.name=megrine-crt
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-3.pooler.supabase.com:6543/postgres?user=postgres.bzcupmwoshqoegtjkque&password=Crtmegrine26&sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.thymeleaf.cache=true
server.port=${PORT:8080}
